# Generated by Django 2.0.2 on 2018-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAccount', '0002_auto_20180216_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
